$(document).ready(function(){
    $('.header__bottom__container_left button').on('click',function(){
        $('.list_category').slideToggle(300)
    })
    $('.slider').owlCarousel({
        loop:true,
        margin:0,
        nav:false,
        autoplay:true,
        items:1,
        dots:false,

    })
    $('.own_client').owlCarousel({
        dots:false,
        loop:true,
        margin:0,
        nav:false,
        autoplay:true,
        items:1,
    })
    $('.npbt').owlCarousel({
        dots:false,
        loop:true,
        margin:10,
        nav:false,
        autoplay:true,
        responsive:{
            0:{
                items:1
            },
            766:{
                items:2
            },
            992:{
                items:4
            }
        }
    })
    $('.latest_new_bottom').owlCarousel({
        dots:false,
        loop:true,
        margin:10,
        nav:false,
        autoplay:true,
        responsive:{
            0:{
                items:1
            },
            766:{
                items:2
            },
            992:{
                items:3
            }
        }
    })
    $('.tcbt').owlCarousel({
        dots:false,
        loop:true,
        margin:10,
        nav:false,
        autoplay:true,
        responsive:{
            0:{
                items:1
            },
            766:{
                items:2
            },
            992:{
                items:4
            }
        }
    })
    
    $('.more_logo_container').owlCarousel({
        dots:false,
        loop:true,
        margin:10,
        nav:false,
        autoplay:true,
        responsive:{
            0:{
                items:2
            },
            766:{
                items:4
            },
            992:{
                items:5
            }
        }
    })
    $('#formDemo').validate({
        rules: {
            email:{
                required:true,
                email:true
            }
        }

    })
    $('.hot').on('click', function(){
        $(this).css({'color':'var(--colorhover--)'})
        $('.top_category2_bottom1').css({'display':'flex'})
        $('.top_category2_bottom2').css({'display':'none'})
        $('.top_category2_bottom3').css({'display':'none'})
        $(this).siblings().css({'color':'#000000'})
    })
    $('.sport').on('click', function(){
        $(this).css({'color':'var(--colorhover--)'})
        $('.top_category2_bottom2').css({'display':'flex'})
        $('.top_category2_bottom1').css({'display':'none'})
        $('.top_category2_bottom3').css({'display':'none'})
        $(this).siblings().css({'color':'#000000'})
    })
    $('.faction').on('click', function(){
        $(this).css({'color':'var(--colorhover--)'})
        $('.top_category2_bottom3').css({'display':'flex'})
        $('.top_category2_bottom1').css({'display':'none'})
        $('.top_category2_bottom2').css({'display':'none'})
        $(this).siblings().css({'color':'#000000'})
    })
    $('.bar').on('click',function(){
        $('.menu_responsive').fadeIn()
        $('.menu__responsive__container').removeClass('animate__slideOutLeft')
        $('.menu__responsive__container').addClass('animate__slideInLeft')
        var vHeight = $('body').height()
        $('.menu_responsive').css({'height':vHeight})
    })
    $('.close').on('click',function(){
        $('.menu_responsive').fadeOut()
        $('.menu__responsive__container').removeClass('animate__slideInLeft')
        $('.menu__responsive__container').addClass('animate__slideOutLeft')
    })
    $('.plus').on('click',function(){
        $(this).css({'display':'none'})
        $(this).next().css({'display':'inline-block'})
        $(this).siblings('ul').slideToggle()
    })
    $('.minus').on('click',function(){
        $(this).css({'display':'none'})
        $(this).prev().css({'display':'inline-block'})
        $(this).siblings('ul').slideToggle()
    })
    $('.tcbt_item').hover(function(){
        $('.tcbt_item_icon').addClass('animate__animated')
        $('.tcbt_item_icon').addClass('animate__fadeInUp')
    })
    $('.npbt_item').hover(function(){
        $('.npbt_item_icon').addClass('animate__animated')
        $('.npbt_item_icon').addClass('animate__fadeInUp')
    })
    $(window).on('scroll',function(){
        if($(this).scrollTop()>=300){
            $('.back-to-top').css({'display':'block'})
            $('.back-to-top').fadeIn(300)
        }
        else{
            $('.back-to-top').fadeOut(300)
        }
    })
    $('.back-to-top').on('click', function(){
        $('html').animate({
            scrollTop :0
        },500)
    })
})